name: Smoke Tests - PR

on:
    pull_request:
        branches: [ main ]

jobs:
    RunTest:
        runs-on: ubuntu-latest

        steps:
            - name: Clonar o projeto
              uses: actions/checkout@v4

            - name: Instalar Java 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'adopt'
                cache: 'maven'

            - name: Run Testes
              env:
                is_pipeline: true
              run: mvn test -Dtest=Runner -Dbrowser=firefox -Dheadless=true -Dis_pipeline=true